import {Home} from "./Home"
import {Dashboard} from "./Dashboard"
import {Settings} from "./Settings"
import {Massages} from "./Massages"
import {Time} from "./Time"
import {Close} from "./Close"
import {Bell} from "./Bell"
import {Appetizer} from "./Appetizer"
import {ColdDishes} from "./ColdDishes"
import {Desert} from "./Desert"
import {HotDishes} from "./HotDishes"
import {Soup} from "./Soup"
import {Grill} from "./Grill"
import {Appereans } from "./Apperens"
import {Restaurant} from "./Restaurant"
import {Product} from "./Product"
import {Notifications} from "./Notificaions"
import {Security} from "./Security"
import {About} from "./About"
export {Appetizer,About,Security, Appereans, Product, Notifications, Restaurant, Grill,Soup,HotDishes,Desert,ColdDishes, Home, Dashboard, Settings, Massages, Time,Bell, Close}